name: Node CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      MSG: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        env:
          CI: false
        run: |
          CHK="Deploy:"
          if [[ "$MSG" == *"$CHK"* ]]; then
            sudo npm install -g yarn
            cd docs
            yarn install
            yarn build
            git config user.email "nimishshah2000@gmail.com"
            git config user.name "sudonims"
            git remote set-url --push origin https://sudonims:$GITHUB_TOKEN@github.com/sudonims/vtop-da-deadline
            git switch gh-pages
            shopt -s extglob
            rm -rf !("docs"|"CNAME")
            cp -r docs/build/* .;
            rm -r docs
            touch .nojekyll
            git add .;
            git commit -am "staged deploy"
            git push origin gh-pages
          fi
          echo "Done."
